package com.example.index_market.bot.utils;

public enum BotStatus {
    START,
    GET_ALL_PRODUCTS,
    ORDER_GET_PHONE_NUMBER,
    ORDER_GET_NAME,
    ORDER_GET_ADDRESS,
    CONSULTATION,
    CONSULTATION_GET_NAME,
    CONSULTATION_GET_PHONE_NUMBER,
    GET_ALL_ORDERS,
    ADMIN, SEND_PASSWORD, SHOW_MORE

}
